### ISSUE TITLE
Plugin always fails: "panic: Helper function must return a string or a SafeString: encryptAES"

### ISSUE THREAD

**Issue by ArBleiziMor** [drone-plugins/drone-pushover#17]
Since the last update (two weeks ago) this plugin always fails with the following error:

```
latest: Pulling from plugins/pushover
Digest: sha256:8960d23f0a732a29b680188432166b0b070006b054f2dd3d9f86c75a03b06c11
Status: Downloaded newer image for plugins/pushover:latest

panic: Helper function must return a string or a SafeString: encryptAES

goroutine 1 [running]:
github.com/aymerick/raymond.ensureValidHelper({0x816c05, 0xa}, {0x7b8480?, 0x84c218?, 0xc00019a000?})
        /go/pkg/mod/github.com/aymerick/raymond@v2.0.2+incompatible/helper.go:68 +0xd3
github.com/aymerick/raymond.RegisterHelper({0x816c05, 0xa}, {0x7b8480?, 0x84c218})
        /go/pkg/mod/github.com/aymerick/raymond@v2.0.2+incompatible/helper.go:47 +0x1d3
github.com/aymerick/raymond.RegisterHelpers(...)
        /go/pkg/mod/github.com/aymerick/raymond@v2.0.2+incompatible/helper.go:55
github.com/drone/drone-template-lib/template.init.0()
        /go/pkg/mod/github.com/drone/drone-template-lib@v1.0.0/template/helpers.go:55 +0x387
```

Could you please take a look?

I love this plugin and I don't want to live without it anymore. Thanks in advance!

**Comment by samcro1967** [comment]
@ArBleiziMor Seems like this puling might have been abandoned????   Did you find a working alternative?
